<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body class="p-4">

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
            <?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?>
                <form action="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login'), null, true) ?>" method="post">
                    <div class="mb-3">
                        <label for="autor" class="form-label">Login</label>
                        <input type="text" class="form-control" id="login" name="login" placeholder="Informe o nome de usuário">
                    </div>
                    <div class="mb-3">
                        <label for="curso" class="form-label">Senha</label>
                        <input type="text" class="form-control" id="senha" name="senha" placeholder="Informe a senha">
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                    <a href="<?php echo $this->url(array('controller' => 'googleauth', 'action' => 'login',)); ?>" class="btn btn-info"><i class="material-icons">google</i></a>
                    
                </form>
            </div>
        </div>
    </div>
</body>

</html>