<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body class="p-4">

    <div class="container">
    <button onclick="window.location='<?php echo $this->url(array('controller' => 'crud', 'action' => 'exibir')); ?>'" class="btn btn-success mb-3">
            <i class="bi bi-plus"></i> Exibir
        </button>
        <button onclick="window.location='<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>'" class="btn btn-success mb-3">
            <i class="bi bi-plus"></i> Logout
        </button>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form action="<?php echo $this->url(array('controller' => 'Crud', 'action' => 'criar'), null, true) ?>" method="post">
                    <div class="mb-3">
                        <label for="autor" class="form-label">Autor</label>
                        <input type="text" class="form-control" id="autor" name="autor" placeholder="Informe o autor">
                    </div>
                    <div class="mb-3">
                        <label for="curso" class="form-label">Curso</label>
                        <input type="text" class="form-control" id="curso" name="curso" placeholder="Informe o curso">
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                    
                </form>
            </div>
        </div>
    </div>
</body>

</html>