<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body class="p-4">
    <div class="container">
        <button onclick="window.location='<?php echo $this->url(array('controller' => 'crud', 'action' => 'criar')); ?>'" class="btn btn-success mb-3">
            <i class="bi bi-plus"></i> Criar
        </button>
        <button onclick="window.location='<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>'" class="btn btn-success mb-3">
            <i class="bi bi-plus"></i> Logout
        </button>
        <table class="table">
            <thead>
                <tr>
                    <th>Autor</th>
                    <th>Curso</th>
                    <th>Funções</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados as $registro) : ?>
                    <tr>
                        <td><?php echo $registro['autor']; ?></td>
                        <td><?php echo $registro['curso']; ?></td>
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'crud', 'action' => 'exibiredicao', 'id' => $registro['id'])); ?>" class="btn btn-info"><i class="material-icons">editar</i></a>
                            <a href="<?php echo $this->url(array('controller' => 'crud', 'action' => 'excluir', 'id' => $registro['id']), null, true); ?>" class="btn btn-danger"><i class="material-icons">delete</i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</body>

</html>