<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form action="<?php echo $this->url(array('controller' => 'crud', 'action' => 'editar'), null, true) ?>" method="post">
                    <div class="mb-3">
                        <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $this->registro['id']; ?>">
                        <!-- Certifique-se de que o input inclua o atributo "name" com o valor correspondente ao campo no banco de dados -->
                        <input type="text" class="form-control" id="autor" name="autor" placeholder="Informe o autor" value="<?php echo $this->registro['autor']; ?>">
                    </div>
                    <div class="mb-3">
                        <!-- Certifique-se de que o input inclua o atributo "name" com o valor correspondente ao campo no banco de dados -->
                        <input type="text" class="form-control" id="curso" name="curso" placeholder="Informe o curso" value="<?php echo $this->registro['curso']; ?>">
                    </div>
                    <button type="submit" class="btn btn-primary">Editar</button>
                </form>
            </div>
        </div>
    </div>
</body>

</html>